### ISSUE TITLE
[1.16.5] Problem with message sending

### ISSUE THREAD

**Issue by ghost** [gyurix/SpigotLib#12]
**Hello.**

I have a problem with message sending.
**Version:** latest 1.16.5 Spigot, latest SpigotLib

**TestPlugin.java:**
```java
public class TestPlugin extends JavaPlugin implements Listener {
    private GlobalLangFile.PluginLang lang;

    public void onEnable() {
        SU.saveResources(this, "lang.yml");
        getServer().getPluginManager().registerEvents(this, this);
        lang = GlobalLangFile.loadLF("TestPlugin", this.getDataFolder() + File.separator + "lang.yml");
    }

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        this.lang.msg(event.getPlayer(), "testMessage");
    }
}
```

**lang.yml:**
```yaml
en:
  TestPlugin:
    prefix: &a[TestPluign] &r
    testMessage: Test message.
```

**Error:**
```
java.lang.NullPointerException
java.lang.NullPointerException
	at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:203)
	at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
	at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:42)
	at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:12)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at gyurix.protocol.manager.ProtocolImpl$ClientChannelHook.write(ProtocolImpl.java:214)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:409)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**1.15.2:**

![img_1](https://user-images.githubusercontent.com/79054592/107883452-522f4200-6eef-11eb-83e6-aa994f08aaf1.PNG)

**Comment by zozidalom** [comment]
Hi,

SpigotLib is no longer actively maintained. 
For 1.16 and above use this fork: https://www.spigotmc.org/resources/thenewspigotlib.88160/
