### ISSUE TITLE
Update SpigotLib to 1.20

### ISSUE THREAD

**Issue by Minecreator200** [gyurix/SpigotLib#14]
Please **consider updating SpigotLib to 1.19** or even better 1.20 as a customer I service paid money for a Stargate plugin from you.

I updated it for him to version 1.20 and everything would work if SpigotLib was also compatible with the newer versions.

Anyone who has a **plugin from you that is based on SpigotLib will no longer be able to use it**, which is a shame.

Please, gyurix and zozidalom, update SpigotLib to version 1.20 or at least 1.19.

That is the **only correct thing to do**.

Have a nice day!

Minecreator200

**Comment by CtrlAiDel** [comment]
I second this please, I'd love to see an update soon! 

This is the error im getting in console:

"[00:00:50 ERROR]: Error occurred while enabling SpigotLib v10.2.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "listener" is null
	at io.papermc.paper.plugin.manager.PaperEventManager.createRegisteredListeners(PaperEventManager.java:136) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:83) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[paper-1.20.1.jar:git-Paper-96]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:670) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at gyurix.spigotlib.Main.onEnable(Main.java:275) ~[SpigotLib.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-96]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-96]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-96]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:00:50 INFO]: [SpigotLib] Disabling SpigotLib v10.2.6"


Thank you minecrator200 for opening this issue!
