### ISSUE TITLE
PlayerQuitEvent error 

### ISSUE THREAD

**Issue by WolverStones** [gyurix/SpigotLib#8]
`[14:14:23 ERROR]: Could not pass event PlayerQuitEvent to SpigotLib v10.1.0
java.lang.NullPointerException: null
at gyurix.scoreboard.ScoreboardAPI.playerLeave(ScoreboardAPI.java:23) ~[?:?]
at gyurix.spigotlib.Main.onPlayerLeave(Main.java:384) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor233.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-67]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-67]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-67]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:410) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1501) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.NetworkManager.handleDisconnection(NetworkManager.java:356) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-67]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-67]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

git-Paper-67 (MC: 1.15.2)

**Comment by zozidalom** [comment]
@MrMorganCz Enable _forceReducedMode_ in the config file of SpigotLib until a fix is released!

**Comment by WolverStones** [comment]
> @MrMorganCz Enable _forceReducedMode_ in the config file of SpigotLib until a fix is released!

Thanks
